cache:
  paths:
    - node_modules/

stages:
  - build
  - dockerize

services:
  - docker:dind

build:
  stage: build
  image: node:8
  script:
    - yarn
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - package.json
      - yarn.lock
      - .yarnclean
      - Dockerfile
      - .dockerignore
      - server.js
      - ./config

dockerize:
  stage: dockerize
  image: docker:latest
  when: on_success
  variables:
    GIT_STRATEGY: none
  only:
    - master
  script:
    - ls -ltr
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN registry.gitlab.com/unicron-lab
    - docker build -t registry.gitlab.com/unicron-lab/unicron-gateway:$CI_JOB_ID .
    - docker push registry.gitlab.com/unicron-lab/unicron-gateway
